##关于端口号和url的访问前缀的配置
server:
  port: 8080
  servlet:
    context-path: /girl

#查看springboot开启了哪些配置
#debug: true

#配置日志输出
logging:
#  pattern:
  #path和file不能同时使用（如使用path则会在指定目录下面创建一个spring.log文件）
  #path: /ToolSoftWare/IDEA/WorkSpace/MyProject/girl/logs/ #日志输出目录
  #日志输出到的文件
#    file: logs/girl.log
  #日志输出级别为debug(日志只输出大于等于debug级别的)
  level:
    org:
      mybatis: debug
    dao: debug
  config: src/main/resources/logback-dev.xml

spring:
  #datasource驱动配置
  datasource:
    name: devgirl
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath*:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.yangpeng.girl.entity
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

#热部署生效
#spring.devtools.restart.enabled: true
#设置重启的目录(让devtools监听指定文件夹)
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**

#日志的路径和项目名
logback:
  logPath: logs/
  appName: girl

cupSize: B
age: 18
##在配置中在使用配置
content: "cupSize: ${cupSize},age: ${age}}"
##将配置分组||将配置写到一个类里面去（推荐）
girl:
  cupSize: B
  age: 18


