##关于端口号和url的访问前缀的配置
server:
  port: 8080
  servlet:
    context-path: /girl

#配置日志输出
logging:
  pattern:
  #path和file不能同时使用（如使用path则会在指定目录下面创建一个spring.log文件）
  #path: /ToolSoftWare/IDEA/WorkSpace/MyProject/girl/logs/ #日志输出目录
  #日志输出到的文件
#    file: logs/girl.log
  #日志输出级别为debug(日志只输出大于等于debug级别的)
#  level: debug
  config: src/main/resources/logback-spring.xml
debug: true #程序运行时开启调试

#日志的路径和项目名
logback:
  logPath: logs/
  appName: girl

cupSize: B
age: 18
##在配置中在使用配置
content: "cupSize: ${cupSize},age: ${age}}"
##将配置分组||将配置写到一个类里面去（推荐）
girl:
  cupSize: B
  age: 18


