##关于端口号和url的访问前缀的配置
server:
  port: 8080
  servlet:
    context-path: /girl
cupSize: B
age: 18
##在配置中在使用配置
content: "cupSize: ${cupSize},age: ${age}}"
##将配置分组||将配置写到一个类里面去（推荐）
girl:
  cupSize: B
  age: 18

#配置日志输出
logging:
  pattern:
  path: /ToolSoftWare/IDEA/WorkSpace/MyProject/girl/logs/ #日志输出目录
  file: /ToolSoftWare/IDEA/WorkSpace/MyProject/girl/logs/girl.log #日志输出文件

