##关于端口号和url的访问前缀的配置
server:
  port: 8080
  servlet:
    context-path: /girl

#查看springboot开启了哪些配置
#debug: true

#配置日志输出
logging:
#  pattern:
  #path和file不能同时使用（如使用path则会在指定目录下面创建一个spring.log文件）
  #path: /ToolSoftWare/IDEA/WorkSpace/MyProject/girl/logs/ #日志输出目录
  #日志输出到的文件
#    file: logs/girl.log
  #日志输出级别为debug(日志只输出大于等于debug级别的)
  level:
    org:
      mybatis: debug
    dao: debug
  config: src/main/resources/logback-dev.xml

spring:
  #datasource的配置
  datasource:
    name: devgirl
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456

#mybatis的配置
mybatis:
  #mybatis 对应的 .xml文件路径
  mapper-locations: classpath*:mapper/*.xml
  #扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.yangpeng.girl.entity

#热部署生效
#spring.devtools.restart.enabled: true
#设置重启的目录(让devtools监听指定文件夹)
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**

#日志的路径和项目名
logback:
  logPath: logs/
  appName: girl

cupSize: B
age: 18
##在配置中在使用配置
content: "cupSize: ${cupSize},age: ${age}}"
##将配置分组||将配置写到一个类里面去（推荐）
girl:
  cupSize: B
  age: 18


